package com.lushprojects.circuitjs1.client;

import com.lushprojects.circuitjs1.client.io.SFCRExporter;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.parallel.ResourceLock;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@ResourceLock("SFCRParser")
@DisplayName("Equation table SFCR export format")
class EquationTableSfcrExportFormatTest extends CircuitJavaSimTestBase {

    @Test
    @DisplayName("R-style export omits autogenerated eN argument names")
    void rStyleExportOmitsAutogeneratedEquationArgumentNames() throws Exception {
        String source =
                "@equations Demo x=200 y=120\n" +
                "  Y ~ 1 ; mode=param\n" +
                "  Z ~ last(Y) + 2\n" +
                "@end\n";

        loadCircuitText(source);

        String exported = new SFCRExporter(sim, SFCRExporter.ExportSyntax.R_STYLE).export();

        assertTrue(exported.contains("Demo <- sfcr_set("), "Expected R-style equations block");
        assertTrue(exported.contains("  Y ~ 1"), "Expected bare equation row without generated argument name");
        assertTrue(exported.contains("  Z ~ last(Y) + 2"), "Expected second bare equation row without generated argument name");
        assertFalse(exported.contains("e1 ="), "Export should not include autogenerated e1 argument name");
        assertFalse(exported.contains("e2 ="), "Export should not include autogenerated e2 argument name");
    }

    @Test
    @DisplayName("block export omits standalone hints when equation comments already cover them")
    void blockExportOmitsStandaloneHintsWhenEquationCommentsCoverThem() throws Exception {
        String source =
                "@equations Demo x=200 y=120\n" +
                "  Y ~ 1  # Output level\n" +
                "@end\n\n" +
                "@hints\n" +
                "  Y: Output level\n" +
                "@end\n";

        loadCircuitText(source);
        sim.getSFCRDocumentManager().setModelInfoSourceText(null);

        String exported = new SFCRExporter(sim, SFCRExporter.ExportSyntax.BLOCK_FORMAT).export();

        assertTrue(exported.contains("Y ~ 1 ; mode=voltage  # Output level"),
                "Expected the hint to stay inline on the equation row");
        assertFalse(exported.contains("Y: Output level"),
                "Export should omit a redundant standalone hint entry for the equation-row hint: " + exported);
    }
}