package com.lushprojects.circuitjs1.client.ui;
import com.lushprojects.circuitjs1.client.*;
import com.lushprojects.circuitjs1.client.util.*;

import com.lushprojects.circuitjs1.client.elements.economics.InfoViewerTableMarkdown;

public final class InfoViewerHtmlBuilder {
    private InfoViewerHtmlBuilder() {
    }

    private static void appendLines(StringBuilder out, String... lines) {
        for (int i = 0; i < lines.length; i++) {
            out.append(lines[i]).append('\n');
        }
    }

    public static String generateMarkdownViewerHTMLPublic(String title, String markdown) {
        return generateMarkdownViewerHTML(title, markdown);
    }

    public static String generateMarkdownViewerHTML(String title, String markdown) {
        return generateMarkdownViewerHTML(title, markdown, markdown, false, true, true);
    }

    public static String generateMarkdownViewerHTML(String title, String markdown, String sourceMarkdown, boolean editable) {
        return generateMarkdownViewerHTML(title, markdown, sourceMarkdown, editable, true, true);
    }

    public static String generateMarkdownViewerHTML(String title, String markdown, String sourceMarkdown,
            boolean editable, boolean parseCodeFenceConstructs, boolean renderSfcrConstructTables) {

        StringBuilder html = new StringBuilder();
        
        // Escape the markdown for embedding in JavaScript
        String escapedMarkdown = escapeForJS(markdown);
        String escapedSourceMarkdown = escapeForJS(sourceMarkdown);
        String escapedAutoTemplateMarkdown = editable ? escapeForJS(InfoViewerTableMarkdown.generateAutoInfoTemplateMarkdown()) : "";
        
        appendHtmlHead(html, title);
        appendLines(html,
            "  <style>",
            "    body { ",
            "      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;",
            "      margin: 0; padding: 16px; background: #fafbfc; color: #24292f; font-size: 13px;",
            "      line-height: 1.4; height: 100vh; overflow: hidden; box-sizing: border-box;",
            "    }",
            "    .container { max-width: 1100px; margin: 0 auto; background: white; padding: 20px; border-radius: 6px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); height: 100%; box-sizing: border-box; display: flex; flex-direction: column; overflow: hidden; }",
            "    h1 { color: #24292f; border-bottom: 1px solid #d0d7de; padding-bottom: 8px; margin: 0 0 16px 0; font-size: 24px; font-weight: 600; }",
            "    h2 { color: #24292f; margin: 24px 0 12px 0; font-size: 18px; font-weight: 600; border-bottom: 1px solid #e5e9ec; padding-bottom: 6px; }",
            "    h3 { color: #57606a; margin: 16px 0 8px 0; font-size: 15px; font-weight: 600; }",
            "    code { background: transparent; padding: 0; font-family: 'SF Mono', 'Consolas', 'Monaco', monospace; font-size: 12px; color: #24292f; }",
            "    pre { background: #f6f8fa; color: #24292f; padding: 12px; border-radius: 4px; overflow-x: auto; border: 1px solid #d0d7de; }",
            "    pre code { background: none; padding: 0; color: inherit; border: none; }",
            "    table { border-collapse: collapse; width: 100%; margin: 10px 0; font-size: 12px; }",
            "    th, td { border: 1px solid #d0d7de; padding: 4px 8px; text-align: left; }",
            "    th { background: #f6f8fa; color: #24292f; font-weight: 600; }",
            "    tr:nth-child(even) { background: #f9fafb; }",
            "    tr:hover { background: #f3f4f6; }",
            "    td code:not(:empty):first-child { display: block; }",
            "    td code:not(:empty) { color: #24292f; }",
            "    td code:not(:empty)[style*='color'] { font-weight: 500; }",
            "    blockquote { border-left: 3px solid #58a6ff; margin: 12px 0; padding: 8px 16px; background: #f6f8fa; color: #57606a; }",
            "    a { color: #0969da; text-decoration: none; }",
            "    a:hover { text-decoration: underline; }",
            "    ul, ol { padding-left: 24px; margin: 8px 0; }",
            "    li { margin: 4px 0; }",
            "    p { margin: 8px 0; }",
            "    hr { border: none; border-top: 1px solid #d0d7de; margin: 24px 0; }",
            "    .export-buttons { margin-bottom: 16px; display: flex; gap: 8px; }",
            "    .export-btn { padding: 6px 12px; background: #2da44e; color: white; border: none; border-radius: 6px; cursor: pointer; font-size: 13px; font-weight: 500; transition: background 0.2s; }",
            "    .export-btn:hover { background: #2c974b; }",
            "    .export-btn:active { background: #298a41; }",
            "    .export-btn.secondary { background: #6c757d; }",
            "    .export-btn.secondary:hover { background: #5c636a; }",
            "    .export-btn.secondary:active { background: #565e64; }",
            "    .export-btn.tertiary { background: #1f6feb; }",
            "    .export-btn.tertiary:hover { background: #1a5fc8; }",
            "    .export-btn.tertiary:active { background: #174ea6; }",
            "    .viewer-option { display: inline-flex; align-items: center; gap: 5px; font-size: 12px; color: #57606a; margin-left: 6px; white-space: nowrap; }",
            "    .viewer-option input { margin: 0; }",
            "    .sim-toolbar-btn { padding: 4px 12px; font-size: 13px; font-weight: 500; border: 1px solid rgba(150, 150, 150, 0.5); border-radius: 4px; background: linear-gradient(to bottom, rgba(255,255,255,0.9) 0%, rgba(232,232,232,0.9) 100%); cursor: pointer; color: #333; transition: all 0.2s ease; white-space: nowrap; vertical-align: middle; display: inline-block; line-height: 1.2; }",
            "    .sim-toolbar-btn:hover { background: linear-gradient(to bottom, #fff 0%, #d0d0d0 100%); border-color: #666; box-shadow: 0 1px 4px rgba(0,0,0,0.2); transform: translateY(-1px); }",
            "    .sim-toolbar-btn:active { background: linear-gradient(to bottom, #d0d0d0 0%, #e8e8e8 100%); box-shadow: inset 0 1px 2px rgba(0,0,0,0.2); transform: translateY(0); }",
            "    .sim-toolbar-btn-stopped { background: linear-gradient(to bottom, #ff6b6b 0%, #ee5a5a 100%); border-color: #d32f2f; color: #fff; }",
            "    .sim-toolbar-btn-stopped:hover { background: linear-gradient(to bottom, #ff8a8a 0%, #ff6b6b 100%); border-color: #d32f2f; }",
            "    .sim-toolbar-btn-running { background: linear-gradient(to bottom, #66bb6a 0%, #4caf50 100%); border-color: #388e3c; color: #fff; }",
            "    .sim-toolbar-btn-running:hover { background: linear-gradient(to bottom, #81c784 0%, #66bb6a 100%); border-color: #388e3c; }",
            "    .viewer-content { display: flex; gap: 12px; align-items: stretch; flex: 1; min-height: 0; overflow: hidden; }",
            "    .editor-pane { flex: 1 1 50%; min-width: 0; display: none; flex-direction: column; min-height: 0; }",
            "    .editor-pane.visible { display: flex; }",
            "    .editor-toolbar { margin-bottom: 8px; display: flex; gap: 8px; }",
            "    .editor-textarea { width: 100%; flex: 1; min-height: 0; box-sizing: border-box; padding: 10px; font-family: 'SF Mono', 'Consolas', 'Monaco', monospace; font-size: 12px; border: 1px solid #d0d7de; border-radius: 4px; resize: none; }",
            "    .preview-pane { flex: 1 1 50%; min-width: 0; min-height: 0; overflow: auto; }",
            "    /* Page break handling for PDF and PNG */",
            "    h2, h3 { page-break-after: avoid; break-after: avoid; }",
            "    table { page-break-inside: avoid; break-inside: avoid; }",
            "    .table-section { page-break-inside: avoid; break-inside: avoid; margin-bottom: 20px; }",
            "    .circuit-table-wrap { margin: 12px 0; }",
            "    .circuit-table-title { font-size: 14px; font-weight: 600; margin-bottom: 8px; color: #24292f; }",
            "    .circuit-table-live { width: 100%; border-collapse: collapse; font-size: 13px; }",
            "    .circuit-table-live th, .circuit-table-live td { border: 1px solid #d0d7de; padding: 6px 8px; text-align: right; }",
            "    .circuit-table-live th:first-child, .circuit-table-live td:first-child { text-align: left; }",
            "    .circuit-table-live thead th { background: #f6f8fa; font-weight: 600; }",
            "    .circuit-table-status { color: #57606a; font-size: 12px; font-style: italic; }",
            "    .circuit-plot-wrap { margin: 12px 0; }",
            "    .circuit-plot-title { font-size: 14px; font-weight: 600; margin-bottom: 8px; color: #24292f; }",
            "    .circuit-plot-mount { width: 100%; height: 320px; border: 1px solid #d0d7de; border-radius: 6px; background: #fff; }",
            "    .circuit-plot-status { color: #57606a; font-size: 12px; font-style: italic; margin-top: 6px; }",
            "    .circuit-sankey-wrap { margin: 12px 0; overflow: visible; position: relative; }",
            "    .circuit-sankey-title { font-size: 14px; font-weight: 600; margin-bottom: 6px; color: #24292f; }",
            "    .circuit-sankey-status { color: #57606a; font-size: 12px; font-style: italic; padding: 12px 0; }",
            "    .circuit-sankey-tooltip { position: absolute; pointer-events: none; z-index: 10; background: rgba(0,0,0,0.82); color: #fff; font-size: 11px; line-height: 1.25; padding: 6px 8px; border-radius: 4px; max-width: 260px; white-space: normal; display: none; }",
            "    @media print { ",
            "      .export-buttons { display: none; }",
            "      body { background: white; }",
            "      .container { box-shadow: none; max-width: 100%; padding: 10px; height: auto; display: block; }",
            "      h2, h3 { page-break-after: avoid; break-after: avoid; }",
            "      table { page-break-inside: avoid; break-inside: avoid; }",
            "      tr { page-break-inside: avoid; break-inside: avoid; }",
            "    }",
            "  </style>"
        );
        appendBodyStructure(html, editable);
        appendScriptVariables(html, escapedMarkdown, escapedSourceMarkdown, escapedAutoTemplateMarkdown,
                      editable, parseCodeFenceConstructs, renderSfcrConstructTables);
        appendLines(html,
            "    var liveValues = {};",
            "    var liveTables = [];",
            "    var liveSankeys = {};",
            "    var liveScopes = {};",
            "    var nextCircuitPlotId = 1;",
            "    var simRunning = false;",
            "    function updateRunStopButton() {",
            "      const btn = document.getElementById('simRunStopBtn');",
            "      if (!btn) return;",
            "      if (simRunning) {",
            "        btn.textContent = 'Stop';",
            "        btn.classList.remove('sim-toolbar-btn-stopped');",
            "        btn.classList.add('sim-toolbar-btn-running');",
            "      } else {",
            "        btn.textContent = 'Run';",
            "        btn.classList.remove('sim-toolbar-btn-running');",
            "        btn.classList.add('sim-toolbar-btn-stopped');",
            "      }",
            "    }",
            "    function formatLiveValue(v) {",
            "      if (v === null || v === undefined || Number.isNaN(v)) return '—';",
            "      if (typeof v !== 'number') return String(v);",
            "      if (!Number.isFinite(v)) return String(v);",
            "      const absV = Math.abs(v);",
            "      if ((absV >= 10000 || (absV > 0 && absV < 0.0001))) return v.toExponential(4);",
            "      return v.toFixed(4).replace(/\\.?0+$/, '');",
            "    }",
            "    function updateLiveValueSpans() {",
            "      const spans = document.querySelectorAll('[data-live-var]');",
            "      spans.forEach(function(span) {",
            "        const key = span.getAttribute('data-live-var');",
            "        if (!key) return;",
            "        if (Object.prototype.hasOwnProperty.call(liveValues, key)) {",
            "          span.textContent = formatLiveValue(liveValues[key]);",
            "        }",
            "      });",
            "    }",
            "    function bindLiveValuePlaceholders(root) {",
            "      if (!root) return;",
            "      const textNodes = [];",
            "      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null, false);",
            "      let node = walker.nextNode();",
            "      while (node) {",
            "        textNodes.push(node);",
            "        node = walker.nextNode();",
            "      }",
            "",
            "      const tokenRegex = /\\{\\{\\s*([A-Za-z0-9_.-]+)\\s*\\}\\}/g;",
            "      textNodes.forEach(function(textNode) {",
            "        const raw = textNode.nodeValue || '';",
            "        if (raw.indexOf('{{') < 0) return;",
            "",
            "        let p = textNode.parentNode;",
            "        let skip = false;",
            "        while (p && p !== root) {",
            "          const tag = (p.nodeName || '').toUpperCase();",
            "          if (tag === 'CODE' || tag === 'PRE' || tag === 'SCRIPT' || tag === 'STYLE') {",
            "            skip = true;",
            "            break;",
            "          }",
            "          p = p.parentNode;",
            "        }",
            "        if (skip || !textNode.parentNode) return;",
            "",
            "        tokenRegex.lastIndex = 0;",
            "        let match;",
            "        let last = 0;",
            "        let changed = false;",
            "        const frag = document.createDocumentFragment();",
            "",
            "        while ((match = tokenRegex.exec(raw)) !== null) {",
            "          changed = true;",
            "          const start = match.index;",
            "          if (start > last) {",
            "            frag.appendChild(document.createTextNode(raw.substring(last, start)));",
            "          }",
            "          const varName = match[1];",
            "          const span = document.createElement('span');",
            "          span.setAttribute('data-live-var', varName);",
            "          span.textContent = formatLiveValue(liveValues[varName]);",
            "          frag.appendChild(span);",
            "          last = tokenRegex.lastIndex;",
            "        }",
            "",
            "        if (!changed) return;",
            "        if (last < raw.length) {",
            "          frag.appendChild(document.createTextNode(raw.substring(last)));",
            "        }",
            "        textNode.parentNode.replaceChild(frag, textNode);",
            "      });",
            "    }",
            "    function escapeHtml(text) {",
            "      if (text === null || text === undefined) return '';",
            "      return String(text)",
            "        .replace(/&/g, '&amp;')",
            "        .replace(/</g, '&lt;')",
            "        .replace(/>/g, '&gt;')",
            "        .replace(/\\\"/g, '&quot;')",
            "        .replace(/'/g, '&#39;');",
            "    }",
            "    function renderGreekAndSubscripts(text) {",
            "      const greek = { alpha: 'α', beta: 'β', gamma: 'γ', delta: 'δ', epsilon: 'ε', zeta: 'ζ', eta: 'η', theta: 'θ',",
            "        iota: 'ι', kappa: 'κ', lambda: 'λ', mu: 'μ', nu: 'ν', xi: 'ξ', omicron: 'ο', pi: 'π', rho: 'ρ', sigma: 'σ',",
            "        tau: 'τ', upsilon: 'υ', phi: 'φ', chi: 'χ', psi: 'ψ', omega: 'ω', Gamma: 'Γ', Delta: 'Δ', Theta: 'Θ',",
            "        Lambda: 'Λ', Xi: 'Ξ', Pi: 'Π', Sigma: 'Σ', Upsilon: 'Υ', Phi: 'Φ', Psi: 'Ψ', Omega: 'Ω' };",
            "      let s = escapeHtml(text);",
            "      s = s.replace(/\\\\([A-Za-z]+)/g, function(_m, name) {",
            "        return Object.prototype.hasOwnProperty.call(greek, name) ? greek[name] : name;",
            "      });",
            "      // Long-form LaTeX-style groups",
            "      s = s.replace(/_\\{([^}]+)\\}/g, '<sub>$1</sub>');",
            "      s = s.replace(/\\^\\{([^}]+)\\}/g, '<sup>$1</sup>');",
            "      // Short-form single-token markers",
            "      s = s.replace(/([A-Za-zΑ-Ωα-ω0-9\\)\\]])_([A-Za-z0-9]+)/g, '$1<sub>$2</sub>');",
            "      s = s.replace(/([A-Za-zΑ-Ωα-ω0-9\\)\\]])\\^([A-Za-z0-9+-]+)/g, '$1<sup>$2</sup>');",
            "      return s;",
            "    }",
            "    function normalizeTableName(name) {",
            "      return (name || '').trim().toLowerCase();",
            "    }",
            "    function canonicalizeTableName(name) {",
            "      const norm = normalizeTableName(name);",
            "      return norm.replace(/[^a-z0-9]+/g, '');",
            "    }",
            "    function parseCircuitTableName(codeText) {",
            "      if (!codeText) return null;",
            "      const lines = String(codeText).split(/\\r?\\n/);",
            "      for (let i = 0; i < lines.length; i++) {",
            "        let m = lines[i].match(/^\\s*table\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) {",
            "          if (m[1].trim() === '*') return 'ALL_TABLES';",
            "          return m[1];",
            "        }",
            "        m = lines[i].match(/^\\s*tables\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) {",
            "          if (/^all$/i.test(m[1].trim())) return 'ALL_TABLES';",
            "        }",
            "      }",
            "      return null;",
            "    }",
            "    function parseSfcrConstructNames(codeText) {",
            "      if (!codeText) return [];",
            "      const names = [];",
            "      const re = /(^|\\n)\\s*@?([A-Za-z_][A-Za-z0-9_]*)\\s*<-\\s*(sfcr_[A-Za-z0-9_]+)\\s*\\(/g;",
            "      let m;",
            "      while ((m = re.exec(String(codeText))) !== null) {",
            "        const name = (m[2] || '').trim();",
            "        if (name && names.indexOf(name) < 0) names.push(name);",
            "      }",
            "      return names;",
            "    }",
            "    function parseCircuitPlotConfig(codeText) {",
            "      if (!codeText) return null;",
            "      const lines = String(codeText).split(/\\r?\\n/);",
            "      let vars = null;",
            "      let title = '';",
            "      let xaxis = 'Time';",
            "      let yaxis = 'Value';",
            "      let windowSize = 200;",
            "      let legend = true;",
            "      let style = 'line';",
            "      let xmin = null;",
            "      let xmax = null;",
            "      let ymin = null;",
            "      let ymax = null;",
            "      for (let i = 0; i < lines.length; i++) {",
            "        const line = lines[i];",
            "        if (/^\\s*@plot\\b/i.test(line)) { continue; }",
            "        if (/^\\s*@end\\s*$/i.test(line)) { continue; }",
            "        let m = line.match(/^\\s*plot\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) {",
            "          vars = m[1].split(',').map(function(v){ return v.trim(); }).filter(function(v){ return v.length > 0; });",
            "          continue;",
            "        }",
            "        m = line.match(/^\\s*vars\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) {",
            "          vars = m[1].split(',').map(function(v){ return v.trim(); }).filter(function(v){ return v.length > 0; });",
            "          continue;",
            "        }",
            "        m = line.match(/^\\s*title\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { title = m[1]; continue; }",
            "        m = line.match(/^\\s*xaxis\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { xaxis = m[1]; continue; }",
            "        m = line.match(/^\\s*xlabel\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { xaxis = m[1]; continue; }",
            "        m = line.match(/^\\s*yaxis\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { yaxis = m[1]; continue; }",
            "        m = line.match(/^\\s*ylabel\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { yaxis = m[1]; continue; }",
            "        m = line.match(/^\\s*window\\s*:\\s*(\\d+)\\s*$/i);",
            "        if (m) {",
            "          const w = parseInt(m[1], 10);",
            "          if (!Number.isNaN(w) && w > 0) windowSize = w;",
            "          continue;",
            "        }",
            "        m = line.match(/^\\s*points\\s*:\\s*(\\d+)\\s*$/i);",
            "        if (m) {",
            "          const w = parseInt(m[1], 10);",
            "          if (!Number.isNaN(w) && w > 0) windowSize = w;",
            "          continue;",
            "        }",
            "        m = line.match(/^\\s*legend\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) {",
            "          const lv = (m[1] || '').trim().toLowerCase();",
            "          legend = !(lv === 'false' || lv === '0' || lv === 'no' || lv === 'off');",
            "          continue;",
            "        }",
            "        m = line.match(/^\\s*style\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { style = (m[1] || '').trim().toLowerCase(); continue; }",
            "        m = line.match(/^\\s*xrange\\s*:\\s*([^,]+?)\\s*,\\s*([^,]+?)\\s*$/i);",
            "        if (m) {",
            "          const x0 = parseFloat((m[1] || '').trim());",
            "          const x1 = parseFloat((m[2] || '').trim());",
            "          if (!Number.isNaN(x0)) xmin = x0;",
            "          if (!Number.isNaN(x1)) xmax = x1;",
            "          continue;",
            "        }",
            "        m = line.match(/^\\s*yrange\\s*:\\s*([^,]+?)\\s*,\\s*([^,]+?)\\s*$/i);",
            "        if (m) {",
            "          const y0 = parseFloat((m[1] || '').trim());",
            "          const y1 = parseFloat((m[2] || '').trim());",
            "          if (!Number.isNaN(y0)) ymin = y0;",
            "          if (!Number.isNaN(y1)) ymax = y1;",
            "          continue;",
            "        }",
            "        m = line.match(/^\\s*xmin\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { const v = parseFloat((m[1] || '').trim()); if (!Number.isNaN(v)) xmin = v; continue; }",
            "        m = line.match(/^\\s*xmax\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { const v = parseFloat((m[1] || '').trim()); if (!Number.isNaN(v)) xmax = v; continue; }",
            "        m = line.match(/^\\s*ymin\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { const v = parseFloat((m[1] || '').trim()); if (!Number.isNaN(v)) ymin = v; continue; }",
            "        m = line.match(/^\\s*ymax\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { const v = parseFloat((m[1] || '').trim()); if (!Number.isNaN(v)) ymax = v; continue; }",
            "      }",
            "      if (xmin !== null && xmax !== null && xmin > xmax) { const t = xmin; xmin = xmax; xmax = t; }",
            "      if (ymin !== null && ymax !== null && ymin > ymax) { const t = ymin; ymin = ymax; ymax = t; }",
            "      const xRange = (xmin !== null && xmax !== null) ? [xmin, xmax] : null;",
            "      const yRange = (ymin !== null && ymax !== null) ? [ymin, ymax] : null;",
            "      if (!vars || vars.length === 0) return null;",
            "      return { vars: vars, title: title, xaxis: xaxis, yaxis: yaxis, windowSize: windowSize, legend: legend, style: style, xRange: xRange, yRange: yRange };",
            "    }",
            "    function parseCircuitScopeConfig(codeText) {",
            "      if (!codeText) return null;",
            "      const lines = String(codeText).split(/\\r?\\n/);",
            "      let scopeName = null;",
            "      let title = '';",
            "      let yaxis = 'Value';",
            "      let windowSize = 200;",
            "      for (let i = 0; i < lines.length; i++) {",
            "        const line = lines[i];",
            "        let m = line.match(/^\\s*@scope\\s+(.+?)\\s*$/i);",
            "        if (m) {",
            "          let raw = (m[1] || '').trim();",
            "          const posIdx = raw.toLowerCase().indexOf(' position=');",
            "          if (posIdx > 0) raw = raw.substring(0, posIdx).trim();",
            "          if (raw) scopeName = raw;",
            "          continue;",
            "        }",
            "        m = line.match(/^\\s*title\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { title = m[1]; continue; }",
            "        m = line.match(/^\\s*yaxis\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { yaxis = m[1]; continue; }",
            "        m = line.match(/^\\s*window\\s*:\\s*(\\d+)\\s*$/i);",
            "        if (m) {",
            "          const w = parseInt(m[1], 10);",
            "          if (!Number.isNaN(w) && w > 0) windowSize = w;",
            "          continue;",
            "        }",
            "      }",
            "      if (!scopeName) return null;",
            "      return { scopeName: scopeName, title: title, yaxis: yaxis, windowSize: windowSize };",
            "    }",
            "    function findLiveScopeByName(scopeName) {",
            "      const wanted = normalizeTableName(scopeName);",
            "      if (!wanted) return null;",
            "      if (Object.prototype.hasOwnProperty.call(liveScopes, wanted)) return liveScopes[wanted];",
            "      const wantedCanon = canonicalizeTableName(scopeName);",
            "      const keys = Object.keys(liveScopes);",
            "      for (let i = 0; i < keys.length; i++) {",
            "        if (canonicalizeTableName(keys[i]) === wantedCanon) return liveScopes[keys[i]];",
            "      }",
            "      return null;",
            "    }",
            "    function findLiveTableByName(tableName) {",
            "      const wanted = normalizeTableName(tableName);",
            "      if (!wanted) return null;",
            "      const wantedCanon = canonicalizeTableName(tableName);",
            "",
            "      // 1) Exact normalized match",
            "      for (let i = 0; i < liveTables.length; i++) {",
            "        const t = liveTables[i];",
            "        if (normalizeTableName(t && t.name) === wanted) return t;",
            "      }",
            "",
            "      // 2) Canonical match (ignore spaces, punctuation, underscore/hyphen differences)",
            "      if (wantedCanon) {",
            "        for (let i = 0; i < liveTables.length; i++) {",
            "          const t = liveTables[i];",
            "          if (canonicalizeTableName(t && t.name) === wantedCanon) return t;",
            "        }",
            "      }",
            "",
            "      // 3) Fallback contains match for small naming drifts",
            "      if (wantedCanon && wantedCanon.length >= 4) {",
            "        for (let i = 0; i < liveTables.length; i++) {",
            "          const t = liveTables[i];",
            "          const tableCanon = canonicalizeTableName(t && t.name);",
            "          if (!tableCanon) continue;",
            "          if (tableCanon.indexOf(wantedCanon) >= 0 || wantedCanon.indexOf(tableCanon) >= 0) return t;",
            "        }",
            "      }",
            "",
            "      return null;",
            "    }",
            "    function isAllTablesToken(name) {",
            "      const n = normalizeTableName(name);",
            "      return n === 'all_tables' || n === 'all-tables' || n === 'alltables' || n === 'all' || n === '*';",
            "    }",
            "    function renderCircuitTableMount(mount) {",
            "      if (!mount) return;",
            "      const tableName = mount.getAttribute('data-circuit-table') || '';",
            "      const table = findLiveTableByName(tableName);",
            "      if (!table) {",
            "        mount.innerHTML = '<div class=\"circuit-table-wrap\"><div class=\"circuit-table-title\">' + escapeHtml(tableName) + '</div><div class=\"circuit-table-status\">Waiting for live table data…</div></div>';",
            "        return;",
            "      }",
            "      const cols = Array.isArray(table.cols) ? table.cols : [];",
            "      const rowNames = Array.isArray(table.rowNames) ? table.rowNames : [];",
            "      const values = Array.isArray(table.values) ? table.values : [];",
            "      const labels = Array.isArray(table.labels) ? table.labels : [];",
            "      const hints = Array.isArray(table.hints) ? table.hints : [];",
            "      const tableType = (table.type || '').toLowerCase();",
            "      let html = '<div class=\"circuit-table-wrap\">';",
            "      html += '<div class=\"circuit-table-title\">' + renderGreekAndSubscripts(table.name || tableName) + '</div>';",
            "      if (tableType === 'equation') {",
            "        html += '<table class=\"circuit-table-live\"><thead><tr><th>Output</th><th>Equation</th><th>Hint</th></tr></thead><tbody>';",
            "        for (let r = 0; r < rowNames.length; r++) {",
            "          const outputName = rowNames[r] || '';",
            "          const rowVals = Array.isArray(values[r]) ? values[r] : [];",
            "          const rowLabels = Array.isArray(labels[r]) ? labels[r] : [];",
            "          const equationText = (rowLabels[0] || '').trim();",
            "          const v = rowVals[0];",
            "          const formattedValue = (typeof v === 'number') ? formatLiveValue(v) : '—';",
            "          const eqCell = equationText ? (renderGreekAndSubscripts(equationText) + ' = ' + escapeHtml(formattedValue)) : escapeHtml(formattedValue);",
            "          const isNegative = (typeof v === 'number' && v < 0);",
            "          const eqStyle = isNegative ? ' style=\\\"color:#cf222e\\\"' : '';",
            "          const hintText = hints[r] || '';",
            "          html += '<tr>';",
            "          html += '<td>' + renderGreekAndSubscripts(outputName) + '</td>';",
            "          html += '<td' + eqStyle + '>' + eqCell + '</td>';",
            "          html += '<td>' + renderGreekAndSubscripts(hintText) + '</td>';",
            "          html += '</tr>';",
            "        }",
            "        html += '</tbody></table></div>';",
            "        mount.innerHTML = html;",
            "        return;",
            "      }",
            "      html += '<table class=\"circuit-table-live\"><thead><tr><th>Flow/Stock</th>';",
            "      for (let c = 0; c < cols.length; c++) html += '<th>' + renderGreekAndSubscripts(cols[c]) + '</th>';",
            "      html += '</tr></thead><tbody>';",
            "      for (let r = 0; r < rowNames.length; r++) {",
            "        html += '<tr><td>' + renderGreekAndSubscripts(rowNames[r]) + '</td>';",
            "        const rowVals = Array.isArray(values[r]) ? values[r] : [];",
            "        const rowLabels = Array.isArray(labels[r]) ? labels[r] : [];",
            "        for (let c = 0; c < cols.length; c++) {",
            "          const v = rowVals[c];",
            "          const label = (rowLabels[c] || '').trim();",
            "          const formattedValue = (typeof v === 'number') ? formatLiveValue(v) : '—';",
            "          const cell = label ? (renderGreekAndSubscripts(label) + ' = ' + escapeHtml(formattedValue)) : '';",
            "          const isNegative = (typeof v === 'number' && v < 0);",
            "          const tdStyle = isNegative ? ' style=\\\"color:#cf222e\\\"' : '';",
            "          html += '<td' + tdStyle + '>' + cell + '</td>';",
            "        }",
            "        html += '</tr>';",
            "      }",
            "      html += '</tbody></table></div>';",
            "      mount.innerHTML = html;",
            "    }",
            "    function updateCircuitTableMounts() {",
            "      const mounts = document.querySelectorAll('[data-circuit-table]');",
            "      mounts.forEach(function(mount) {",
            "        const tableName = mount.getAttribute('data-circuit-table') || '';",
            "        if (isAllTablesToken(tableName)) {",
            "          if (!liveTables || liveTables.length === 0) {",
            "            mount.innerHTML = '<div class=\\\"circuit-table-wrap\\\"><div class=\\\"circuit-table-title\\\">All Tables</div><div class=\\\"circuit-table-status\\\">Waiting for live table data…</div></div>';",
            "            return;",
            "          }",
            "          let html = '';",
            "          for (let i = 0; i < liveTables.length; i++) {",
            "            const t = liveTables[i];",
            "            if (!t || !t.name) continue;",
            "            html += '<div data-circuit-table=\\\"' + escapeHtml(t.name) + '\\\"></div>';",
            "          }",
            "          mount.innerHTML = html;",
            "          const nested = mount.querySelectorAll('[data-circuit-table]');",
            "          nested.forEach(function(nm) { renderCircuitTableMount(nm); });",
            "          return;",
            "        }",
            "        renderCircuitTableMount(mount);",
            "      });",
            "    }",
            "    function ensureCircuitPlotInitialized(mount, cfg) {",
            "      if (!window.Plotly || !cfg || !cfg.vars || cfg.vars.length === 0) {",
            "        mount.innerHTML = '<div class=\\\"circuit-plot-status\\\">Plotly unavailable or invalid plot config.</div>';",
            "        return false;",
            "      }",
            "      if (mount.__plotInitialized) return true;",
            "      const style = (cfg.style || 'line').toLowerCase();",
            "      const mode = (style === 'scatter' || style === 'points' || style === 'markers') ? 'markers' : ((style === 'line+points' || style === 'lines+points' || style === 'both') ? 'lines+markers' : 'lines');",
            "      const traces = cfg.vars.map(function(name) {",
            "        return { x: [], y: [], mode: mode, type: 'scatter', name: name, line: { width: 2 } };",
            "      });",
            "      const layout = {",
            "        title: cfg.title || ('Plot: ' + cfg.vars.join(', ')),",
            "        xaxis: { title: cfg.xaxis || 'Time', gridcolor: '#ddd' },",
            "        yaxis: { title: cfg.yaxis || 'Value', gridcolor: '#ddd' },",
            "        margin: { l: 56, r: 16, t: 48, b: 42 },",
            "        paper_bgcolor: '#fff',",
            "        plot_bgcolor: '#fff',",
            "        showlegend: cfg.legend !== false,",
            "        legend: { orientation: 'h' }",
            "      };",
            "      if (Array.isArray(cfg.xRange) && cfg.xRange.length === 2) {",
            "        layout.xaxis.range = [cfg.xRange[0], cfg.xRange[1]];",
            "        layout.xaxis.autorange = false;",
            "      }",
            "      if (Array.isArray(cfg.yRange) && cfg.yRange.length === 2) {",
            "        layout.yaxis.range = [cfg.yRange[0], cfg.yRange[1]];",
            "        layout.yaxis.autorange = false;",
            "      }",
            "      const config = { responsive: true, displaylogo: false };",
            "      Plotly.newPlot(mount.id, traces, layout, config);",
            "      mount.__plotInitialized = true;",
            "      return true;",
            "    }",
            "    function updateCircuitPlotMounts(explicitTime) {",
            "      const mounts = document.querySelectorAll('[data-circuit-plot]');",
            "      mounts.forEach(function(mount) {",
            "        const cfgText = mount.getAttribute('data-circuit-plot') || '';",
            "        let cfg = null;",
            "        try { cfg = JSON.parse(cfgText); } catch (e) { cfg = null; }",
            "        if (!cfg || !cfg.vars || cfg.vars.length === 0) return;",
            "        if (!ensureCircuitPlotInitialized(mount, cfg)) return;",
            "",
            "        const t = (typeof explicitTime === 'number') ? explicitTime : (typeof liveValues.t === 'number' ? liveValues.t : null);",
            "        if (typeof t === 'number' && mount.__lastPlotT === t) return;",
            "",
            "        const xVal = (typeof t === 'number') ? t : ((mount.__plotPointIndex || 0) + 1);",
            "        mount.__plotPointIndex = xVal;",
            "        if (typeof t === 'number') mount.__lastPlotT = t;",
            "",
            "        const xArr = [];",
            "        const yArr = [];",
            "        const traceIdx = [];",
            "        for (let i = 0; i < cfg.vars.length; i++) {",
            "          const name = cfg.vars[i];",
            "          const yVal = Object.prototype.hasOwnProperty.call(liveValues, name) ? liveValues[name] : null;",
            "          xArr.push([xVal]);",
            "          yArr.push([typeof yVal === 'number' ? yVal : null]);",
            "          traceIdx.push(i);",
            "        }",
            "",
            "        Plotly.extendTraces(mount.id, { x: xArr, y: yArr }, traceIdx, cfg.windowSize || 200);",
            "      });",
            "    }",
            "    function clearCircuitPlotMounts() {",
            "      const mounts = document.querySelectorAll('[data-circuit-plot]');",
            "      mounts.forEach(function(mount) {",
            "        mount.__plotInitialized = false;",
            "        mount.__lastPlotT = null;",
            "        mount.__plotPointIndex = 0;",
            "        if (window.Plotly && mount.id) {",
            "          try { Plotly.purge(mount.id); } catch (e) {}",
            "        }",
            "      });",
            "      updateCircuitPlotMounts();",
            "    }",
            "    function installCircuitTableMounts() {",
            "      if (!renderSfcrConstructTables) return;",
            "      const content = document.getElementById('content');",
            "      if (!content) return;",
            "      const codeBlocks = content.querySelectorAll('pre > code');",
            "      codeBlocks.forEach(function(code) {",
            "        const tableName = parseCircuitTableName(code.textContent || '');",
            "        let tableNames = [];",
            "        if (tableName) tableNames.push(tableName);",
            "        if (tableNames.length === 0 && renderSfcrConstructTables && parseCodeFenceConstructs) {",
            "          tableNames = parseSfcrConstructNames(code.textContent || '');",
            "        }",
            "        if (tableNames.length === 0) return;",
            "        const mountWrap = document.createElement('div');",
            "        for (let i = 0; i < tableNames.length; i++) {",
            "          const mount = document.createElement('div');",
            "          mount.setAttribute('data-circuit-table', tableNames[i]);",
            "          mountWrap.appendChild(mount);",
            "        }",
            "        const pre = code.parentElement;",
            "        if (pre && pre.tagName === 'PRE') {",
            "          pre.parentNode.replaceChild(mountWrap, pre);",
            "        } else {",
            "          code.parentNode.replaceChild(mountWrap, code);",
            "        }",
            "      });",
            "      updateCircuitTableMounts();",
            "    }",
            "    function parseCircuitSankeyConfig(codeText) {",
            "      if (!codeText) return null;",
            "      const lines = String(codeText).split(/\\r?\\n/);",
            "      let tableName = null;",
            "      let title = '';",
            "      let width = 600;",
            "      let height = 320;",
            "      let inAtSankey = false;",
            "      for (let i = 0; i < lines.length; i++) {",
            "        const line = lines[i];",
            "        if (/^\\s*@sankey\\b/i.test(line)) { inAtSankey = true; continue; }",
            "        if (inAtSankey && /^\\s*@end\\s*$/i.test(line)) { inAtSankey = false; continue; }",
            "        let m = line.match(/^\\s*sankey\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { tableName = m[1]; continue; }",
            "        m = line.match(/^\\s*source\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { tableName = m[1]; continue; }",
            "        m = line.match(/^\\s*title\\s*:\\s*(.+?)\\s*$/i);",
            "        if (m) { title = m[1]; continue; }",
            "        m = line.match(/^\\s*width\\s*:\\s*(\\d+)\\s*$/i);",
            "        if (m) { const w2 = parseInt(m[1], 10); if (!isNaN(w2) && w2 > 0) width = w2; continue; }",
            "        m = line.match(/^\\s*height\\s*:\\s*(\\d+)\\s*$/i);",
            "        if (m) { const h2 = parseInt(m[1], 10); if (!isNaN(h2) && h2 > 0) height = h2; continue; }",
            "      }",
            "      if (!tableName) return null;",
            "      return { tableName: tableName, title: title, width: width, height: height };",
            "    }",
            "    function findSankeyByName(name) {",
            "      const key = normalizeTableName(name);",
            "      if (Object.prototype.hasOwnProperty.call(liveSankeys, key)) return liveSankeys[key];",
            "      const canon = canonicalizeTableName(name);",
            "      const keys = Object.keys(liveSankeys);",
            "      for (let i = 0; i < keys.length; i++) {",
            "        if (canonicalizeTableName(keys[i]) === canon) return liveSankeys[keys[i]];",
            "      }",
            "      if (canon && canon.length >= 4) {",
            "        for (let i = 0; i < keys.length; i++) {",
            "          const kc = canonicalizeTableName(keys[i]);",
            "          if (kc && (kc.indexOf(canon) >= 0 || canon.indexOf(kc) >= 0)) return liveSankeys[keys[i]];",
            "        }",
            "      }",
            "      return null;",
            "    }",
            "    function renderSankeyInMount(mount, data, cfg) {",
            "      if (!window.d3 || !d3.sankey) {",
            "        mount.innerHTML = '<div class=\"circuit-sankey-status\">D3/d3-sankey not loaded.</div>';",
            "        return;",
            "      }",
            "      mount.innerHTML = '';",
            "      const nodeLabels = data.nodeLabels || [];",
            "      const nodeColors = data.nodeColors || [];",
            "      const linkSources = data.linkSources || [];",
            "      const linkTargets = data.linkTargets || [];",
            "      const linkValues = data.linkValues || [];",
            "      const linkColors = data.linkColors || [];",
            "      const linkLabels = data.linkLabels || [];",
            "      if (!linkSources.length || !nodeLabels.length) {",
            "        mount.innerHTML = '<div class=\"circuit-sankey-status\">No flow data yet — run simulation.</div>';",
            "        return;",
            "      }",
            "      const validLinks = [];",
            "      for (let li = 0; li < linkSources.length; li++) {",
            "        const v = linkValues[li] || 0;",
            "        if (v > 0 && isFinite(v) && !isNaN(v)) {",
            "          validLinks.push({ source: linkSources[li], target: linkTargets[li], value: v, color: linkColors[li], label: linkLabels[li] || '' });",
            "        }",
            "      }",
            "      if (!validLinks.length) {",
            "        mount.innerHTML = '<div class=\"circuit-sankey-status\">No positive flows yet — run simulation.</div>';",
            "        return;",
            "      }",
            "      const titleText = (cfg && cfg.title) ? cfg.title : '';",
            "      const w = (cfg && cfg.width) ? cfg.width : (mount.clientWidth || 600);",
            "      const h = (cfg && cfg.height) ? cfg.height : 320;",
            "      const titleH = titleText ? 22 : 0;",
            "      const margin = { top: titleH + 8, right: 10, bottom: 8, left: 10 };",
            "      const innerW = w - margin.left - margin.right;",
            "      const innerH = h - margin.top - margin.bottom;",
            "      const svg = d3.select(mount).append('svg').attr('width', w).attr('height', h);",
            "      if (titleText) {",
            "        svg.append('text').attr('x', w / 2).attr('y', 15).attr('text-anchor', 'middle')",
            "           .attr('font-size', '13px').attr('font-weight', '600').attr('fill', '#24292f')",
            "           .text(titleText);",
            "      }",
            "      const g = svg.append('g').attr('transform', 'translate(' + margin.left + ',' + margin.top + ')');",
            "      const tooltip = d3.select(mount).append('div').attr('class', 'circuit-sankey-tooltip');",
            "      function showTooltip(html, event) {",
            "        tooltip.style('display', 'block').html(html || '');",
            "        moveTooltip(event);",
            "      }",
            "      function moveTooltip(event) {",
            "        const rect = mount.getBoundingClientRect();",
            "        const x = (event.clientX - rect.left) + 10;",
            "        const y = (event.clientY - rect.top) + 10;",
            "        tooltip.style('left', x + 'px').style('top', y + 'px');",
            "      }",
            "      function hideTooltip() {",
            "        tooltip.style('display', 'none');",
            "      }",
            "      const sankeyLayout = d3.sankey().nodeWidth(14).nodePadding(8)",
            "        .extent([[0, 0], [innerW, innerH]]);",
            "      const d3Nodes = nodeLabels.map(function(name, i) { return { name: name, color: nodeColors[i] || '#1f77b4' }; });",
            "      let graph;",
            "      try {",
            "        graph = sankeyLayout({ nodes: d3Nodes.map(function(d) { return Object.assign({}, d); }),",
            "                              links: validLinks.map(function(d) { return Object.assign({}, d); }) });",
            "      } catch(e) {",
            "        mount.innerHTML = '<div class=\"circuit-sankey-status\">Layout error: ' + escapeHtml(String(e)) + '</div>';",
            "        return;",
            "      }",
            "      g.append('g').selectAll('path').data(graph.links).enter().append('path')",
            "        .attr('d', d3.sankeyLinkHorizontal())",
            "        .attr('fill', 'none')",
            "        .attr('stroke', function(d) { return d.color || '#aaa'; })",
            "        .attr('stroke-width', function(d) { return Math.max(1, d.width || 1); })",
            "        .attr('stroke-opacity', 0.4)",
            "        .on('mouseover', function(event, d) {",
            "          d3.select(this).attr('stroke-opacity', 0.7);",
            "          const src = (d.source && d.source.name) ? d.source.name : '';",
            "          const dst = (d.target && d.target.name) ? d.target.name : '';",
            "          const flowLabel = d.label && d.label.length ? d.label : (src + ' → ' + dst + ': ' + formatLiveValue(d.value));",
            "          showTooltip(escapeHtml(flowLabel), event);",
            "        })",
            "        .on('mousemove', function(event) { moveTooltip(event); })",
            "        .on('mouseout', function() { d3.select(this).attr('stroke-opacity', 0.4); hideTooltip(); });",
            "      const node = g.append('g').selectAll('g').data(graph.nodes).enter().append('g');",
            "      node.append('rect')",
            "        .attr('x', function(d) { return d.x0; })",
            "        .attr('y', function(d) { return d.y0; })",
            "        .attr('width', function(d) { return d.x1 - d.x0; })",
            "        .attr('height', function(d) { return Math.max(1, d.y1 - d.y0); })",
            "        .attr('fill', function(d) { return d.color || '#1f77b4'; })",
            "        .attr('fill-opacity', 0.9)",
            "        .on('mouseover', function(event, d) {",
            "          const inV = (typeof d.value === 'number') ? formatLiveValue(d.value) : '—';",
            "          showTooltip(escapeHtml((d.name || '') + ': ' + inV), event);",
            "        })",
            "        .on('mousemove', function(event) { moveTooltip(event); })",
            "        .on('mouseout', function() { hideTooltip(); });",
            "      node.append('text')",
            "        .attr('x', function(d) { return d.x0 < innerW / 2 ? d.x1 + 5 : d.x0 - 5; })",
            "        .attr('y', function(d) { return (d.y1 + d.y0) / 2; })",
            "        .attr('dy', '0.35em')",
            "        .attr('text-anchor', function(d) { return d.x0 < innerW / 2 ? 'start' : 'end'; })",
            "        .attr('font-size', '11px')",
            "        .attr('fill', '#24292f')",
            "        .text(function(d) { return d.name; });",
            "    }",
            "    function updateCircuitSankeyMounts() {",
            "      const mounts = document.querySelectorAll('[data-circuit-sankey]');",
            "      mounts.forEach(function(mount) {",
            "        const tableName = mount.getAttribute('data-circuit-sankey') || '';",
            "        let cfg = null;",
            "        try { cfg = JSON.parse(mount.getAttribute('data-circuit-sankey-cfg') || '{}'); } catch(e) {}",
            "        const data = findSankeyByName(tableName);",
            "        if (!data) {",
            "          mount.innerHTML = '<div class=\"circuit-sankey-status\">Waiting for Sankey data\u2026</div>';",
            "          return;",
            "        }",
            "        renderSankeyInMount(mount, data, cfg);",
            "      });",
            "    }",
            "    function installCircuitSankeyMounts() {",
            "      if (!renderSfcrConstructTables) return;",
            "      const content = document.getElementById('content');",
            "      if (!content) return;",
            "      const codeBlocks = content.querySelectorAll('pre > code');",
            "      codeBlocks.forEach(function(code) {",
            "        const cfg = parseCircuitSankeyConfig(code.textContent || '');",
            "        if (!cfg) return;",
            "        const wrap = document.createElement('div');",
            "        wrap.className = 'circuit-sankey-wrap';",
            "        wrap.setAttribute('data-circuit-sankey', cfg.tableName);",
            "        wrap.setAttribute('data-circuit-sankey-cfg', JSON.stringify(cfg));",
            "        wrap.style.width = cfg.width + 'px';",
            "        wrap.style.height = cfg.height + 'px';",
            "        const pre = code.parentElement;",
            "        if (pre && pre.tagName === 'PRE') {",
            "          pre.parentNode.replaceChild(wrap, pre);",
            "        } else {",
            "          code.parentNode.replaceChild(wrap, code);",
            "        }",
            "      });",
            "      updateCircuitSankeyMounts();",
            "    }",
            "    function ensureCircuitScopePlotInitialized(mount, cfg, scope) {",
            "      if (!window.Plotly || !cfg || !scope || !Array.isArray(scope.traces) || scope.traces.length === 0) {",
            "        mount.innerHTML = '<div class=\\\"circuit-plot-status\\\">Scope data unavailable.</div>';",
            "        return false;",
            "      }",
            "      const traceNames = scope.traces.map(function(t){ return t && t.name ? t.name : 'Trace'; });",
            "      const sameLayout = Array.isArray(mount.__scopeTraceNames) && mount.__scopeTraceNames.length === traceNames.length",
            "        && mount.__scopeTraceNames.every(function(n, i){ return n === traceNames[i]; });",
            "      if (mount.__scopePlotInitialized && sameLayout) return true;",
            "      const traces = traceNames.map(function(name) { return { x: [], y: [], mode: 'lines', type: 'scatter', name: name, line: { width: 2 } }; });",
            "      const layout = {",
            "        title: cfg.title || (cfg.scopeName || 'Scope'),",
            "        xaxis: { title: 'Time', gridcolor: '#ddd' },",
            "        yaxis: { title: cfg.yaxis || 'Value', gridcolor: '#ddd' },",
            "        margin: { l: 56, r: 16, t: 48, b: 42 },",
            "        paper_bgcolor: '#fff',",
            "        plot_bgcolor: '#fff',",
            "        showlegend: true,",
            "        legend: { orientation: 'h' }",
            "      };",
            "      const config = { responsive: true, displaylogo: false };",
            "      Plotly.newPlot(mount.id, traces, layout, config);",
            "      mount.__scopePlotInitialized = true;",
            "      mount.__scopeTraceNames = traceNames;",
            "      return true;",
            "    }",
            "    function updateCircuitScopeMounts(explicitTime) {",
            "      const mounts = document.querySelectorAll('[data-circuit-scope]');",
            "      mounts.forEach(function(mount) {",
            "        const cfgText = mount.getAttribute('data-circuit-scope') || '';",
            "        let cfg = null;",
            "        try { cfg = JSON.parse(cfgText); } catch (e) { cfg = null; }",
            "        if (!cfg || !cfg.scopeName) return;",
            "        const scope = findLiveScopeByName(cfg.scopeName);",
            "        if (!scope || !Array.isArray(scope.traces) || scope.traces.length === 0) {",
            "          mount.innerHTML = '<div class=\\\"circuit-plot-status\\\">Waiting for scope data…</div>';",
            "          mount.__scopePlotInitialized = false;",
            "          return;",
            "        }",
            "        if (!ensureCircuitScopePlotInitialized(mount, cfg, scope)) return;",
            "        const t = (typeof explicitTime === 'number') ? explicitTime : (typeof liveValues.t === 'number' ? liveValues.t : null);",
            "        if (typeof t === 'number' && mount.__lastScopeT === t) return;",
            "        const xVal = (typeof t === 'number') ? t : ((mount.__scopePointIndex || 0) + 1);",
            "        mount.__scopePointIndex = xVal;",
            "        if (typeof t === 'number') mount.__lastScopeT = t;",
            "        const xArr = [];",
            "        const yArr = [];",
            "        const traceIdx = [];",
            "        for (let i = 0; i < scope.traces.length; i++) {",
            "          const tr = scope.traces[i] || {};",
            "          const yVal = (typeof tr.value === 'number') ? tr.value : null;",
            "          xArr.push([xVal]);",
            "          yArr.push([yVal]);",
            "          traceIdx.push(i);",
            "        }",
            "        Plotly.extendTraces(mount.id, { x: xArr, y: yArr }, traceIdx, cfg.windowSize || 200);",
            "      });",
            "    }",
            "    function clearCircuitScopeMounts() {",
            "      const mounts = document.querySelectorAll('[data-circuit-scope]');",
            "      mounts.forEach(function(mount) {",
            "        mount.__scopePlotInitialized = false;",
            "        mount.__lastScopeT = null;",
            "        mount.__scopePointIndex = 0;",
            "        mount.__scopeTraceNames = null;",
            "        if (window.Plotly && mount.id) {",
            "          try { Plotly.purge(mount.id); } catch (e) {}",
            "        }",
            "      });",
            "      updateCircuitScopeMounts();",
            "    }",
            "    function installCircuitScopeMounts() {",
            "      if (!renderSfcrConstructTables) return;",
            "      const content = document.getElementById('content');",
            "      if (!content) return;",
            "      const codeBlocks = content.querySelectorAll('pre > code');",
            "      codeBlocks.forEach(function(code) {",
            "        const scopeCfg = parseCircuitScopeConfig(code.textContent || '');",
            "        if (!scopeCfg) return;",
            "        const wrap = document.createElement('div');",
            "        wrap.className = 'circuit-plot-wrap';",
            "        const plotDiv = document.createElement('div');",
            "        plotDiv.className = 'circuit-plot-mount';",
            "        plotDiv.id = 'circuit-plot-' + (nextCircuitPlotId++);",
            "        plotDiv.setAttribute('data-circuit-scope', JSON.stringify(scopeCfg));",
            "        wrap.appendChild(plotDiv);",
            "        const pre = code.parentElement;",
            "        if (pre && pre.tagName === 'PRE') {",
            "          pre.parentNode.replaceChild(wrap, pre);",
            "        } else {",
            "          code.parentNode.replaceChild(wrap, code);",
            "        }",
            "      });",
            "      updateCircuitScopeMounts();",
            "    }",
            "    function installCircuitPlotMounts() {",
            "      if (!renderSfcrConstructTables) return;",
            "      const content = document.getElementById('content');",
            "      if (!content) return;",
            "      const codeBlocks = content.querySelectorAll('pre > code');",
            "      codeBlocks.forEach(function(code) {",
            "        const plotCfg = parseCircuitPlotConfig(code.textContent || '');",
            "        if (!plotCfg) return;",
            "",
            "        const wrap = document.createElement('div');",
            "        wrap.className = 'circuit-plot-wrap';",
            "",
            "        const plotDiv = document.createElement('div');",
            "        plotDiv.className = 'circuit-plot-mount';",
            "        plotDiv.id = 'circuit-plot-' + (nextCircuitPlotId++);",
            "        plotDiv.setAttribute('data-circuit-plot', JSON.stringify(plotCfg));",
            "",
            "        wrap.appendChild(plotDiv);",
            "",
            "        const pre = code.parentElement;",
            "        if (pre && pre.tagName === 'PRE') {",
            "          pre.parentNode.replaceChild(wrap, pre);",
            "        } else {",
            "          code.parentNode.replaceChild(wrap, code);",
            "        }",
            "      });",
            "      updateCircuitPlotMounts();",
            "    }",
            "    window.addEventListener('message', function(event) {",
            "      const data = event.data;",
            "      if (!data || data.type !== 'circuit-live') return;",
            "      const prevT = (typeof liveValues.t === 'number') ? liveValues.t : null;",
            "      if (typeof data.running === 'boolean') { simRunning = data.running; updateRunStopButton(); }",
            "      liveValues = data.vars || {};",
            "      liveTables = Array.isArray(data.tables) ? data.tables : [];",
            "      liveSankeys = {};",
            "      const sankeysArr = Array.isArray(data.sankeys) ? data.sankeys : [];",
            "      for (let si = 0; si < sankeysArr.length; si++) {",
            "        const entry = sankeysArr[si];",
            "        if (entry && entry.name) liveSankeys[normalizeTableName(entry.name)] = entry.data;",
            "      }",
            "      liveScopes = {};",
            "      const scopesArr = Array.isArray(data.scopes) ? data.scopes : [];",
            "      for (let spi = 0; spi < scopesArr.length; spi++) {",
            "        const scopeEntry = scopesArr[spi];",
            "        if (scopeEntry && scopeEntry.name) liveScopes[normalizeTableName(scopeEntry.name)] = scopeEntry;",
            "      }",
            "      if (typeof data.t === 'number') liveValues.t = data.t;",
            "      if (typeof data.dt === 'number') liveValues.dt = data.dt;",
            "      if (typeof data.t === 'number' && typeof prevT === 'number' && data.t < prevT) { clearCircuitPlotMounts(); clearCircuitScopeMounts(); }",
            "      updateLiveValueSpans();",
            "      updateCircuitTableMounts();",
            "      updateCircuitPlotMounts(data.t);",
            "      updateCircuitScopeMounts(data.t);",
            "      updateCircuitSankeyMounts();",
            "    });",
            "    function toggleEditor() {",
            "      if (!editorEnabled) return;",
            "      const pane = document.getElementById('editorPane');",
            "      const btn = document.getElementById('toggleEditorBtn');",
            "      if (!pane) return;",
            "      const nowVisible = !pane.classList.contains('visible');",
            "      pane.classList.toggle('visible', nowVisible);",
            "      if (btn) btn.textContent = nowVisible ? '👁️ Hide Editor' : '✏️ Edit Markdown';",
            "      if (nowVisible) {",
            "        const editor = document.getElementById('markdownEditor');",
            "        if (editor) editor.value = sourceMarkdown;",
            "      }",
            "    }",
            "    function applyEditorPreview() {",
            "      const editor = document.getElementById('markdownEditor');",
            "      if (!editor) return;",
            "      sourceMarkdown = editor.value || '';",
            "      markdown = sourceMarkdown;",
            "      renderMarkdown(markdown);",
            "    }",
            "    function generateTemplateFromCircuit() {",
            "      if (!editorEnabled) return;",
            "      const editor = document.getElementById('markdownEditor');",
            "      if (!editor) return;",
            "      const nextTemplate = autoTemplateMarkdown || '';",
            "      if (!nextTemplate.trim()) return;",
            "      const current = editor.value || '';",
            "      const hasExisting = current.trim().length > 0;",
            "      if (hasExisting && !confirm('Append generated template to the current markdown?')) return;",
            "      const merged = hasExisting",
            "        ? current.replace(/\\s*$/, '') + '\\n\\n---\\n\\n' + nextTemplate.replace(/^\\s*/, '')",
            "        : nextTemplate;",
            "      editor.value = merged;",
            "      sourceMarkdown = merged;",
            "      markdown = merged;",
            "      renderMarkdown(markdown);",
            "    }",
            "    function saveMarkdownToCircuit() {",
            "      const editor = document.getElementById('markdownEditor');",
            "      if (!editor) return;",
            "      sourceMarkdown = editor.value || '';",
            "      markdown = sourceMarkdown;",
            "      renderMarkdown(markdown);",
            "      const msg = { type: 'info-viewer-save-markdown', markdown: sourceMarkdown };",
            "      try { if (window.parent) window.parent.postMessage(msg, '*'); } catch (e1) {}",
            "      try { if (window.opener) window.opener.postMessage(msg, '*'); } catch (e2) {}",
            "    }",
            "    function getCircuitApi() {",
            "      try { if (window.parent && window.parent !== window && window.parent.CircuitJS1) return window.parent.CircuitJS1; } catch (e1) {}",
            "      try { if (window.opener && window.opener.CircuitJS1) return window.opener.CircuitJS1; } catch (e2) {}",
            "      try { if (window.CircuitJS1) return window.CircuitJS1; } catch (e3) {}",
            "      return null;",
            "    }",
            "    function sendSimCommand(command) {",
            "      const msg = { type: 'info-viewer-sim-command', command: command };",
            "      try { if (window.parent) window.parent.postMessage(msg, '*'); } catch (e1) {}",
            "      try { if (window.opener) window.opener.postMessage(msg, '*'); } catch (e2) {}",
            "    }",
            "    function sendViewerOptionChanged(key, enabled) {",
            "      const msg = { type: 'info-viewer-option-changed', key: key, enabled: !!enabled };",
            "      try { if (window.parent) window.parent.postMessage(msg, '*'); } catch (e1) {}",
            "      try { if (window.opener) window.opener.postMessage(msg, '*'); } catch (e2) {}",
            "    }",
            "    function simRunStop() {",
            "      const api = getCircuitApi();",
            "      const nextRunning = !simRunning;",
            "      simRunning = nextRunning;",
            "      updateRunStopButton();",
            "      if (api && api.setSimRunning) { api.setSimRunning(nextRunning); return; }",
            "      sendSimCommand(nextRunning ? 'run' : 'stop');",
            "    }",
            "    function simReset() {",
            "      clearCircuitPlotMounts();",
            "      const api = getCircuitApi();",
            "      if (api && api.reset) { api.reset(); return; }",
            "      sendSimCommand('reset');",
            "    }",
            "    function simStep() {",
            "      const api = getCircuitApi();",
            "      simRunning = false;",
            "      updateRunStopButton();",
            "      if (api && api.setSimRunning) api.setSimRunning(false);",
            "      if (api && api.step) { api.step(); return; }",
            "      sendSimCommand('stop');",
            "      sendSimCommand('step');",
            "    }",
            "    function resolveMarkdownHref(href) {",
            "      if (!href) return null;",
            "      if (href.startsWith('#') || href.startsWith('http://') || href.startsWith('https://') || href.startsWith('mailto:') || href.startsWith('data:')) return null;",
            "      var clean = href.split('#')[0].split('?')[0];",
            "      if (!clean || !clean.toLowerCase().endsWith('.md')) return null;",
            "      if (clean.startsWith('/')) return clean.substring(1);",
            "      if (clean.startsWith('doc/')) return clean;",
            "      if (clean.startsWith('./')) clean = clean.substring(2);",
            "      return 'doc/reference/' + clean;",
            "    }",
            "    ",
            "    function attachMarkdownLinkHandlers() {",
            "      const content = document.getElementById('content');",
            "      const links = content.querySelectorAll('a[href]');",
            "      links.forEach(function(link) {",
            "        const href = link.getAttribute('href');",
            "        const mdUrl = resolveMarkdownHref(href);",
            "        if (!mdUrl) return;",
            "        link.addEventListener('click', function(e) {",
            "          e.preventDefault();",
            "          fetch(mdUrl).then(function(resp) {",
            "            if (!resp.ok) throw new Error('HTTP ' + resp.status);",
            "            return resp.text();",
            "          }).then(function(text) {",
            "            renderMarkdown(text);",
            "          }).catch(function(err) {",
            "            const c = document.getElementById('content');",
            "            c.innerHTML = '<p>Failed to load markdown: ' + mdUrl + '</p>';",
            "          });",
            "        });",
            "      });",
            "    }",
            "    ",
            "    function renderMarkdown(md) {",
            "      markdown = md;",
            "      const content = document.getElementById('content');",
            "      // Protect math segments so markdown emphasis parsing doesn't eat '*' inside $...$",
            "      const protectedMath = [];",
            "      const markdownForParse = markdown.replace(/\\$\\$[\\s\\S]*?\\$\\$|\\$[^$\\n]+\\$/g, function(match) {",
            "        const token = '@@MATH_SEGMENT_' + protectedMath.length + '@@';",
            "        protectedMath.push(match);",
            "        return token;",
            "      });",
            "      content.innerHTML = marked.parse(markdownForParse);",
            "      if (protectedMath.length > 0) {",
            "        let restoredHtml = content.innerHTML;",
            "        for (let i = 0; i < protectedMath.length; i++) {",
            "          const token = '@@MATH_SEGMENT_' + i + '@@';",
            "          restoredHtml = restoredHtml.split(token).join(protectedMath[i]);",
            "        }",
            "        content.innerHTML = restoredHtml;",
            "      }",
            "      // Render LaTeX math equations with KaTeX",
            "      renderMathInElement(content, {",
            "        delimiters: [",
            "          {left: '$$', right: '$$', display: true},",
            "          {left: '$', right: '$', display: false},",
            "          {left: '\\\\[', right: '\\\\]', display: true},",
            "          {left: '\\\\(', right: '\\\\)', display: false}",
            "        ],",
            "        throwOnError: false",
            "      });",
            "      bindLiveValuePlaceholders(content);",
            "      installCircuitTableMounts();",
            "      installCircuitPlotMounts();",
            "      installCircuitScopeMounts();",
            "      installCircuitSankeyMounts();",
            "      // Wrap tables in sections for better page breaks, preserving source order",
            "      const tableNodes = Array.from(content.querySelectorAll(':scope > table'));",
            "      tableNodes.forEach(function(tableNode) {",
            "        if (!tableNode || !tableNode.parentNode || tableNode.parentNode !== content) return;",
            "        const section = document.createElement('div');",
            "        section.className = 'table-section';",
            "        const prev = tableNode.previousElementSibling;",
            "        if (prev && prev.tagName === 'H3') {",
            "          prev.parentNode.insertBefore(section, prev);",
            "          section.appendChild(prev);",
            "        } else {",
            "          tableNode.parentNode.insertBefore(section, tableNode);",
            "        }",
            "        section.appendChild(tableNode);",
            "      });",
            "      attachMarkdownLinkHandlers();",
            "      updateLiveValueSpans();",
            "      updateCircuitTableMounts();",
            "      updateCircuitPlotMounts();",
            "      updateCircuitScopeMounts();",
            "      updateCircuitSankeyMounts();",
            "    }",
            "    ",
            "    function loadReferenceIndex() {",
            "      fetch('doc/reference/ReferenceIndex.md').then(function(resp) {",
            "        if (!resp.ok) throw new Error('HTTP ' + resp.status);",
            "        return resp.text();",
            "      }).then(function(text) {",
            "        renderMarkdown(text);",
            "      }).catch(function(err) {",
            "        const c = document.getElementById('content');",
            "        c.innerHTML = '<p>Failed to load reference index.</p>';",
            "      });",
            "    }",
            "    ",
            "    renderMarkdown(markdown);",
            "    updateRunStopButton();",
            "    (function setupViewerOptions(){",
            "      const parseCb = document.getElementById('viewerParseCodeFenceConstructs');",
            "      const renderCb = document.getElementById('viewerRenderSfcrConstructTables');",
            "      if (parseCb) parseCb.checked = !!parseCodeFenceConstructs;",
            "      if (renderCb) renderCb.checked = !renderSfcrConstructTables;",
            "      if (parseCb) {",
            "        parseCb.addEventListener('change', function(){",
            "          parseCodeFenceConstructs = !!parseCb.checked;",
            "          sendViewerOptionChanged('parse-code-fence-constructs', parseCodeFenceConstructs);",
            "          renderMarkdown(markdown);",
            "        });",
            "      }",
            "      if (renderCb) {",
            "        renderCb.addEventListener('change', function(){",
            "          renderSfcrConstructTables = !renderCb.checked;",
            "          sendViewerOptionChanged('render-sfcr-construct-tables', renderSfcrConstructTables);",
            "          renderMarkdown(markdown);",
            "        });",
            "      }",
            "    })();",
            "    (function syncInitialRunState(){",
            "      const api = getCircuitApi();",
            "      if (api && api.isRunning) {",
            "        try { simRunning = !!api.isRunning(); updateRunStopButton(); } catch (e) {}",
            "      }",
            "    })();",
            "    if (editorEnabled) {",
            "      const editor = document.getElementById('markdownEditor');",
            "      if (editor) editor.value = sourceMarkdown;",
            "    }",
            "    ",
            "    ",
            "    function saveToPDF() {",
            "      window.print();",
            "    }",
            "    ",
            "    function saveToPNG() {",
            "      const button = event.target;",
            "      const exportButtons = document.querySelector('.export-buttons');",
            "      button.disabled = true;",
            "      button.textContent = 'Generating...';",
            "      ",
            "      // Hide export buttons during capture",
            "      exportButtons.style.display = 'none';",
            "      ",
            "      const container = document.querySelector('.container');",
            "      const scale = 2;",
            "      ",
            "      // A4 dimensions at 96 DPI (screen resolution)",
            "      const a4Height = 1123; // 297mm",
            "      const timestamp = Date.now();",
            "      ",
            "      // Find natural break points (before table-sections, h2, hr)",
            "      // Only break BEFORE .table-section divs (which contain h3 + table together)",
            "      const containerRect = container.getBoundingClientRect();",
            "      const containerTop = containerRect.top;",
            "      ",
            "      // Get table sections (h3 + table combined) and other block elements",
            "      const tableSections = container.querySelectorAll('.table-section');",
            "      const otherBreaks = container.querySelectorAll('h2, hr');",
            "      const breakPoints = [0]; // Start at 0",
            "      ",
            "      // Add table section starts as break points",
            "      tableSections.forEach(el => {",
            "        const rect = el.getBoundingClientRect();",
            "        const relativeTop = rect.top - containerTop;",
            "        if (relativeTop > 50) breakPoints.push(relativeTop);",
            "      });",
            "      ",
            "      // Add h2 and hr elements as break points",
            "      otherBreaks.forEach(el => {",
            "        const rect = el.getBoundingClientRect();",
            "        const relativeTop = rect.top - containerTop;",
            "        if (relativeTop > 50) breakPoints.push(relativeTop);",
            "      });",
            "      ",
            "      // Sort break points by position",
            "      breakPoints.sort((a, b) => a - b);",
            "      ",
            "      // First, capture the entire content as one big canvas",
            "      html2canvas(container, {",
            "        scale: scale,",
            "        backgroundColor: '#ffffff',",
            "        logging: false,",
            "        useCORS: true",
            "      }).then(fullCanvas => {",
            "        // Show buttons again after capture",
            "        exportButtons.style.display = 'flex';",
            "        ",
            "        const fullHeight = fullCanvas.height;",
            "        const fullWidth = fullCanvas.width;",
            "        const pageHeightPx = a4Height * scale;",
            "        ",
            "        // Find smart page breaks",
            "        const pageBreaks = [0];",
            "        let currentY = 0;",
            "        "
        );
        appendLines(html,
            "        while (currentY < fullHeight) {",
            "          let idealBreak = currentY + pageHeightPx;",
            "          ",
            "          if (idealBreak >= fullHeight) {",
            "            // Last page",
            "            break;",
            "          }",
            "          ",
            "          // Find the best break point near the ideal break",
            "          // Look for a natural break within 15% of page height",
            "          const minBreak = idealBreak - (pageHeightPx * 0.15);",
            "          const maxBreak = idealBreak;",
            "          ",
            "          let bestBreak = idealBreak;",
            "          let foundNatural = false;",
            "          ",
            "          // Search break points in reverse to find one close to but before ideal",
            "          for (let i = breakPoints.length - 1; i >= 0; i--) {",
            "            const bp = breakPoints[i] * scale;",
            "            if (bp >= minBreak && bp <= maxBreak && bp > currentY + (pageHeightPx * 0.5)) {",
            "              bestBreak = bp;",
            "              foundNatural = true;",
            "              break;",
            "            }",
            "          }",
            "          ",
            "          pageBreaks.push(bestBreak);",
            "          currentY = bestBreak;",
            "        }",
            "        ",
            "        pageBreaks.push(fullHeight); // End marker",
            "        const numPages = pageBreaks.length - 1;",
            "        ",
            "        if (numPages === 1) {",
            "          // Single page - just download it",
            "          fullCanvas.toBlob(function(blob) {",
            "            downloadBlob(blob, 'circuit-tables-' + timestamp + '.png');",
            "            button.disabled = false;",
            "            button.textContent = '🖼️ Save as PNG';",
            "          });",
            "          return;",
            "        }",
            "        ",
            "        // Multiple pages - slice and download each",
            "        button.textContent = 'Slicing into ' + numPages + ' pages...';",
            "        ",
            "        let currentPage = 0;",
            "        ",
            "        function downloadNextPage() {",
            "          if (currentPage >= numPages) {",
            "            button.disabled = false;",
            "            button.textContent = '🖼️ Save as PNG';",
            "            return;",
            "          }",
            "          ",
            "          const pageNum = currentPage + 1;",
            "          button.textContent = 'Saving page ' + pageNum + '/' + numPages + '...';",
            "          ",
            "          const yStart = pageBreaks[currentPage];",
            "          const yEnd = pageBreaks[currentPage + 1];",
            "          const sliceHeight = yEnd - yStart;",
            "          ",
            "          // Create a new canvas for this page",
            "          const pageCanvas = document.createElement('canvas');",
            "          pageCanvas.width = fullWidth;",
            "          pageCanvas.height = sliceHeight;",
            "          const ctx = pageCanvas.getContext('2d');",
            "          ",
            "          // Draw the slice from the full canvas",
            "          ctx.drawImage(fullCanvas, 0, yStart, fullWidth, sliceHeight, 0, 0, fullWidth, sliceHeight);",
            "          ",
            "          pageCanvas.toBlob(function(blob) {",
            "            downloadBlob(blob, 'circuit-tables-' + timestamp + '-page-' + pageNum + '.png');",
            "            currentPage++;",
            "            // User must click each time - browsers block multiple auto downloads",
            "            if (currentPage < numPages) {",
            "              button.textContent = '📥 Click for page ' + (currentPage + 1) + '/' + numPages;",
            "              button.disabled = false;",
            "              button.onclick = function(e) {",
            "                e.preventDefault();",
            "                button.disabled = true;",
            "                downloadNextPage();",
            "              };",
            "            } else {",
            "              button.disabled = false;",
            "              button.textContent = '🖼️ Save as PNG';",
            "              button.onclick = function() { saveToPNG(); };",
            "            }",
            "          });",
            "        }",
            "        ",
            "        downloadNextPage();",
            "        ",
            "      }).catch(err => {",
            "        console.error('PNG export error:', err);",
            "        alert('Error generating PNG: ' + err.message);",
            "        button.disabled = false;",
            "        button.textContent = '🖼️ Save as PNG';",
            "      });",
            "    }",
            "    ",
            "    function downloadBlob(blob, filename) {",
            "      const url = URL.createObjectURL(blob);",
            "      const a = document.createElement('a');",
            "      a.href = url;",
            "      a.download = filename;",
            "      document.body.appendChild(a);",
            "      a.click();",
            "      document.body.removeChild(a);",
            "      URL.revokeObjectURL(url);",
            "    }",
            "  </script>",
            "</body>",
            "</html>"
        );
        
        return html.toString();
    
    }

    // -----------------------------------------------------------------------
    // Private HTML structure helpers
    // -----------------------------------------------------------------------

    /** Emits the HTML <head> block: DOCTYPE, meta tags, CDN scripts, and KaTeX. */
    private static void appendHtmlHead(StringBuilder html, String title) {
        appendLines(html,
            "<!DOCTYPE html>",
            "<html lang=\"en\">",
            "<head>",
            "  <meta charset=\"UTF-8\">",
            "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
        );
        appendLines(html, "  <title>" + escapeHtml(title) + "</title>");
        appendLines(html,
            "  <script src=\"https://cdn.jsdelivr.net/npm/marked/marked.min.js\"></script>",
            "  <script src=\"https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js\"></script>",
            "  <script src=\"https://cdn.plot.ly/plotly-2.27.0.min.js\"></script>",
            "  <script src=\"https://d3js.org/d3.v7.min.js\"></script>",
            "  <script src=\"https://cdn.jsdelivr.net/npm/d3-sankey@0.12.3/dist/d3-sankey.min.js\"></script>"
        );
        // KaTeX for math rendering
        appendLines(html,
            "  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css\">",
            "  <script src=\"https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js\"></script>",
            "  <script src=\"https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js\"></script>"
        );
    }

    /** Emits the </head><body> transition, toolbar buttons, editor pane, preview pane, and opens the <script> tag. */
    private static void appendBodyStructure(StringBuilder html, boolean editable) {
        appendLines(html,
            "</head>",
            "<body>",
            "  <div class=\"container\">",
            "    <div class=\"export-buttons\">",
            "      <button class=\"export-btn tertiary\" onclick=\"loadReferenceIndex()\">📚 Back to Index</button>"
        );
        if (editable) {
            appendLines(html,
                "      <button id=\"toggleEditorBtn\" class=\"export-btn secondary\" onclick=\"toggleEditor()\">✏️ Edit Markdown</button>");
        }
        appendLines(html,
            "      <button class=\"export-btn\" onclick=\"saveToPDF()\">📄 Save as PDF</button>",
            "      <button class=\"export-btn secondary\" onclick=\"saveToPNG()\">🖼️ Save as PNG</button>",
            "      <button id=\"simRunStopBtn\" class=\"sim-toolbar-btn sim-toolbar-btn-stopped\" onclick=\"simRunStop()\">Run</button>",
            "      <button class=\"sim-toolbar-btn\" onclick=\"simReset()\">Reset</button>",
            "      <button class=\"sim-toolbar-btn\" onclick=\"simStep()\">Step</button>",
            "      <label class=\"viewer-option\"><input id=\"viewerParseCodeFenceConstructs\" type=\"checkbox\">Load sfcr/@ constructs in code blocks</label>",
            "      <label class=\"viewer-option\"><input id=\"viewerRenderSfcrConstructTables\" type=\"checkbox\">Show raw blocks</label>",
            "    </div>",
            "    <div class=\"viewer-content\">",
            "      <div id=\"editorPane\" class=\"editor-pane\">",
            "        <div class=\"editor-toolbar\">",
            "          <button class=\"export-btn tertiary\" onclick=\"generateTemplateFromCircuit()\">🧩 Append Template</button>",
            "          <button class=\"export-btn secondary\" onclick=\"applyEditorPreview()\">Apply Preview</button>",
            "          <button class=\"export-btn\" onclick=\"saveMarkdownToCircuit()\">Save to Model</button>",
            "        </div>",
            "        <textarea id=\"markdownEditor\" class=\"editor-textarea\"></textarea>",
            "      </div>",
            "      <div class=\"preview-pane\">",
            "        <div id=\"content\">Loading...</div>",
            "      </div>",
            "    </div>",
            "  </div>",
            "  <script>"
        );
    }

    /** Emits the initial JS variable declarations that seed markdown content and editor state. */
    private static void appendScriptVariables(StringBuilder html,
            String escapedMarkdown, String escapedSourceMarkdown,
            String escapedAutoTemplateMarkdown, boolean editable,
            boolean parseCodeFenceConstructs, boolean renderSfcrConstructTables) {
        appendLines(html,
            "    var markdown = \"" + escapedMarkdown + "\";",
            "    var sourceMarkdown = \"" + escapedSourceMarkdown + "\";",
            "    var autoTemplateMarkdown = \"" + escapedAutoTemplateMarkdown + "\";",
            "    var editorEnabled = " + (editable ? "true" : "false") + ";",
            "    var parseCodeFenceConstructs = " + (parseCodeFenceConstructs ? "true" : "false") + ";",
            "    var renderSfcrConstructTables = " + (renderSfcrConstructTables ? "true" : "false") + ";");
    }

    private static String escapeForJS(String text) {
        if (text == null) return "";
        return text
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t");
    }

    private static String escapeHtml(String text) {
        if (text == null) return "";
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;");
    }
}
