name: Deploy Quarto Site

on:
  # Trigger on push to main branch
  push:
    branches: [ main ]
  
  # Trigger on releases from the main circuitjs1 repository
  repository_dispatch:
    types: [ circuitjs1-release ]
    
  # Allow manual triggering
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout documentation repository
      uses: actions/checkout@v4
      
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: pre-release
        
    - name: Setup Node.js (for any JS dependencies)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java (needed to build CircuitJS1)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y ant
        
    - name: Checkout CircuitJS1 source
      uses: actions/checkout@v4
      with:
        repository: johnnewto/circuitjs1  # Replace with actual repo
        path: circuitjs1-source
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build CircuitJS1 application
      run: |
        cd circuitjs1-source
        # Setup GWT if needed
        if [ ! -d "../gwt-2.8.2" ]; then
          cd ..
          wget https://goo.gl/pZZPXS -O gwt-2.8.2.zip
          unzip gwt-2.8.2.zip
          cd circuitjs1-source
        fi
        # Build with ant
        ant build
        
    - name: Copy CircuitJS1 to site
      run: |
        # Copy the built application to the documentation site
        mkdir -p assets/app
        cp circuitjs1-source/war/circuitjs.html assets/app/
        cp -r circuitjs1-source/war/circuitjs1 assets/app/
        cp -r circuitjs1-source/war/*.js assets/app/ || true
        cp -r circuitjs1-source/war/*.css assets/app/ || true
        
        # Update the app.qmd iframe src to point to the copied files
        sed -i 's|src="circuitjs.html"|src="assets/app/circuitjs.html"|g' app.qmd
        
    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4